### ISSUE TITLE
Add capability to retrieve all pages when getting project list

### ISSUE THREAD

**Issue by rachmari** [peter-evans/create-or-update-project-card#26]
We recently ran into an issue when using this action that seemed to indicate that only the first page of projects is returned. It may have been another issue, but I thought I'd file this bug to ask the question. Returning the first page is probably ok most of the time, but we have an organization with hundreds of projects. The action wasn't able to find a project by id and it appeared that not all of the projects were being returned.

**Comment by peter-evans** [comment]
Hi @rachmari 

You are absolutely right, I neglected to paginate the API calls to list projects and columns. Working on a fix for this.

**Comment by peter-evans** [comment]
This should be fixed in the latest release (`v1` / `v1.1.4`)

**Comment by rachmari** [comment]
Thank you for fixing this so quickly @peter-evans! 🙏
