### ISSUE TITLE
How to enable Debug log

### ISSUE THREAD

**Issue by stevejr** [peter-evans/create-or-update-project-card#39]
Hi,

I am trying to get this action to work but it just keeps failing so I would like to see more information as right now errors are not being logged.

Can you please advise how this can be enabled.

**Comment by peter-evans** [comment]
Hi @stevejr 

You can set a secret called `ACTIONS_STEP_DEBUG` to `true`, which will enable debug logging. This is common across GitHub Actions, not just this action.

See the docs here:
https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging
