### ISSUE TITLE
Move multiple cards at once?

### ISSUE THREAD

**Issue by andreacab2** [peter-evans/create-or-update-project-card#47]
Hey,

Thanks for the great github actions plugin. We've found it very useful at our company.

I was wondering if there is a way to move multiple cards at once?

Thanks.

**Comment by peter-evans** [comment]
Hi @andreacab2 

I would like to avoid making the action and its interface more complicated if possible. My inclination would be to solve this in the workflow itself. Please could you share your workflow so I can understand the context.

**Comment by peter-evans** [comment]
I would suggest using the [job matrix](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) construct to execute the action multiple times, one for each issue. You would likely need a prerequisite job to prepare a JSON array of the issue numbers for a dynamic matrix.

This example might help:
https://github.com/suzuki-shunsuke/example-github-actions-dynamic-matrix/blob/master/.github/workflows/test.yml
