### ISSUE TITLE
Integration with pull request.

### ISSUE THREAD

**Issue by Sanchitbajaj02** [peter-evans/create-or-update-project-card#52]
Hey,

Thanks for the amazing and helpful GitHub actions.

I want to know, is there any way to integrate the **create-or-update-project-card** action with your **create-pull-request** action so when someone pushes their code, pull request has been generated as well as it shows the card in projects.

Thanks a lot

**Comment by peter-evans** [comment]
Hi @Sanchitbajaj02 

Yes, you can create a card immediately after creating a pull request with `create-pull-request` action. Please see the example in the docs here:
https://github.com/peter-evans/create-pull-request#create-a-project-card
